-- V1 model alignment migration
-- Purpose: Record that JPA entity relationships were aligned with the existing schema.
--
-- Summary of alignment in code (no DB impact):
-- - Added inverse OneToMany mappings:
--     User.sentMessages (mappedBy sender), User.notifications (mappedBy user)
--     Customer.tickets (mappedBy customer), Staff.assignedTickets (mappedBy assignedStaff)
-- - Ensured Ticket.messages are ordered chronologically with @OrderBy("timestamp ASC").
-- - Exposed Notification.type as EnumType.STRING (column remains VARCHAR(50)).
-- - Confirmed Single Table inheritance for users with discriminator column `role`.
--
-- Keeping a no-op statement so Flyway records this migration.
SELECT 1;